#!/bin/bash

# SlackBuild script to keep google-chrome browser easy up to date...FOR SLACKWARE CURRENT

# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# MIT License
#
# Copyright (c) 2023 Anagnostakis Ioannis
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

if [ "root" != "$USER" ]; then
  su -c "$0" root
  exit
fi

#########################
#***********************#
# FOR SLACKWARE CURRENT*#
#***********************#
######################### 
dir=google-chrome


cd /tmp || exit 1
rm google-chrome-*.t?z
mkdir -p $dir || exit 1
cd $dir || exit 1
rm -r *
lftp -c mirror https://slackware.uk/slackware/slackware64-current/extra/google-chrome/
cd google-chrome || exit 1
wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
chmod +x google-chrome.SlackBuild 
./google-chrome.SlackBuild 
upgradepkg --reinstall --install-new  /tmp/google-chrome-*.t?z
wait
echo 
echo "Well done."
